name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.14
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'Is this pr still needed?'
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Is this still an issue? If yes please comment that it still is.'
        stale-issue-label: 'no-issue-activity'
        exempt-issue-labels: 'enhancement,question,Needs-Info'
        stale-pr-label: 'no-pr-activity'
        exempt-pr-labels: 'awaiting-approval,work-in-progress,PrExempt'
        days-before-stale: 60
        days-before-close: 90
        close-issue-message: 'Please reopen this issue if you are still having what is described above. this issue has been stale for 150 days.' 
